name: Backend Continuous Integration

on:
  workflow_call:
  pull_request:
    paths:
      - 'apps/backend/**'
    branches:
      - main

jobs:
  lint_and_test_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npx nx run atom-challenge-backend:lint
#
#      - name: Run Tests
#        run: npm --prefix ./backend test
