name: Deploy Frontend to Firebase
on:
  workflow_call:
  workflow_dispatch:  # This line allows the workflow to be run manually
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  pull_request:
    types: [ closed ]
    branches:
      - main
    paths:
      - 'frontend/**'
jobs:
  lint_and_test_frontend:
    uses: ./.github/workflows/frontend-ci.yml
  build_and_deploy_frontend:
    #    We also need to deploy first the functions before the hosting
    needs: [ lint_and_test_frontend ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v4

      - name: Install dependencies frontend
        run: npm --prefix ./frontend ci

      - name: Install Firebase CLI & Configure & Deploy Hosting
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/gcloud-service-key.json
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GROOVY_GEARBOX_422522_B1}}' > $GOOGLE_APPLICATION_CREDENTIALS
          npm install -g firebase-tools
          firebase deploy --only hosting
